filters:
  files:
    match:
      - product/app/Browser2/Browser2.apk
      - product/app/Calendar/Calendar.apk
      - product/app/DeviceStatisticsService/DeviceStatisticsService.apk
      - product/app/QuickSearchBox/QuickSearchBox.apk
      - product/app/webview/webview.apk
      - product/etc/permissions/privapp-permissions-soundrecorder.xml
      - product/priv-app/OneTimeInitializer/OneTimeInitializer.apk
      - product/priv-app/QtiSoundRecorder/QtiSoundRecorder.apk
      - product/build.prop
      - system_ext/app/BluetoothDsDaService/BluetoothDsDaService.apk
      - system_ext/app/QCC/QCC.apk
      - system_ext/app/QCC-AUTHMGR/QCC-AUTHMGR.apk
      - system_ext/app/QdcmFF/QdcmFF.apk
      - system_ext/app/aptxacu/aptxacu.apk
      - system_ext/app/aptxui/aptxui.apk
      - system_ext/app/com.qualcomm.qti.services.secureui/com.qualcomm.qti.services.secureui.apk
      - system_ext/app/workloadclassifier/workloadclassifier.apk
      - system_ext/bin/aptxalsOverlayCreateProject.sh
      - system_ext/bin/bt_logger
      - system_ext/bin/dun-server
      - system_ext/etc/init/init.qti.bt.logger.rc
      - system_ext/etc/permissions/com.android.cellbroadcastreceiver.xml
      - system_ext/etc/permissions/com.android.provision.xml
      - system_ext/etc/permissions/privapp-permissions-aptxals.xml
      - system_ext/etc/permissions/privapp-permissions-mms.xml
      - system_ext/etc/permissions/qti_supplicant_interface.xml
      - system_ext/etc/vintf/manifest/vendor.qti.qesdsys.service.xml
      - system_ext/lib/libbluetooth_qti.so
      - system_ext/lib/libbt-logClient.so
      - system_ext/lib/libbtconfigstore.so
      - system_ext/lib/libcomposerextn.qti.so
      - system_ext/lib/libqcomfm_jni.so
      - system_ext/lib/libqti_workloadclassifiermodel.so
      - system_ext/lib/libsecureui_svcsock_system.so
      - system_ext/lib/libsecureuisvc_jni.so
      - system_ext/lib/libsmomoconfig.qti.so
      - system_ext/lib/libsystemhelper_jni.so
      - system_ext/lib/libxrvd.qti.so
      - system_ext/lib64/libadapter.dylib.so
      - system_ext/lib64/libbluetooth_qti.so
      - system_ext/lib64/libbt-logClient.so
      - system_ext/lib64/libbtconfigstore.so
      - system_ext/lib64/libcomposerextn.qti.so
      - system_ext/lib64/libmmio.dylib.so
      - system_ext/lib64/libqcomfm_jni.so
      - system_ext/lib64/libqti_workloadclassifiermodel.so
      - system_ext/lib64/libsecureui_svcsock_system.so
      - system_ext/lib64/libsecureuisvc_jni.so
      - system_ext/lib64/libsmomoconfig.qti.so
      - system_ext/lib64/libsystemhelper_jni.so
      - system_ext/lib64/libxrvd.qti.so
      - system_ext/priv-app/CellBroadcastAppPlatform/CellBroadcastAppPlatform.apk
      - system_ext/priv-app/MSDC_UI/MSDC_UI.apk
      - system_ext/priv-app/Mms/Mms.apk
      - system_ext/priv-app/Provision/Provision.apk
      - system_ext/priv-app/QAS_DVC_MSP/QAS_DVC_MSP.apk
      - system_ext/priv-app/QtiDialer/QtiDialer.apk
      - system_ext/priv-app/aptxals/aptxals.apk
      - system_ext/priv-app/com.qualcomm.qti.services.systemhelper/lib/arm64/libsystemhelper_jni.so
      - system_ext/priv-app/com.qualcomm.qti.services.systemhelper/com.qualcomm.qti.services.systemhelper.apk
      - system_ext/build.prop
      - vendor/bin/hw/android.hardware.biometrics.face@1.0-service.faceauth
      - vendor/bin/hw/android.hardware.boot@1.1-service
      - vendor/bin/hw/android.hardware.usb@1.2-service-qti
      - vendor/default.prop
      - vendor/etc/init/hw/init.wpa_supplicant.rc
      - vendor/etc/init/android.hardware.biometrics.face@1.0-service.faceauth.rc
      - vendor/etc/init/android.hardware.boot@1.1-service.rc
      - vendor/etc/init/android.hardware.usb@1.2-service-qti.rc
      - vendor/etc/vintf/manifest/android.hardware.boot@1.1.xml
      - vendor/etc/vintf/manifest/android.hardware.usb@1.2-service.xml
      - vendor/etc/vintf/manifest/manifest.xml
      - vendor/lib/hw/android.hardware.boot@1.0-impl-1.1-qti.so
      - vendor/lib64/hw/android.hardware.boot@1.0-impl-1.1-qti.so

    prefix:
      - product/etc/selinux/
      - system/
      - system_ext/etc/bluetooth/
      - system_ext/etc/selinux/
      - vendor/etc/selinux/
      - vendor/lib/vndk/

  # Resource overlay APK file names (to work around aapt2 parsing bugs)
  # Only base file name, not full path.
  overlay_files:
    match:
      - aptxalsOverlay.apk

  overlay_keys:
    match:
      - android:string/config_availableColorModes
      - com.android.phone:string/dialer_default_class
      - com.android.settings:string/config_color_mode_options_strings
      - com.android.settings:string/config_color_mode_options_values

  overlay_values:
    substring:
      # QCOM Dialer
      - org.codeaurora.dialer

  props:
    match:
      - persist.sys.usb.config
      - ro.bluetooth.library_name
      - ro.bootimage.build.date
      - ro.bootimage.build.date.utc
      - ro.bootimage.build.fingerprint
      - ro.build.keys
      - ro.build.product.name
      - ro.build.system_root_image
      - ro.product.board

    prefix:
      # adevtool doesn't play nicely with imports so exclude them.
      - import

  sepolicy_dirs:
    match:
      - device/qcom/sepolicy/generic/prebuilts/api/31.0/private
      - device/qcom/sepolicy/generic/prebuilts/api/32.0/private
      - device/qcom/sepolicy/generic/private
      - device/qcom/sepolicy_vndr/legacy/vendor/common

      # Exclude userdebug policies.
      - device/qcom/sepolicy_vndr/generic/vendor/test
